### ISSUE TITLE
Previous controller is invoked even after mvcGroupDestroy

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#109]
Hi,

I think the reason is that custom event listener is not destroyed automatically in mvcGroupDestroy()
My scenario is:

1. PreferenceGrp is [m,v,c] and represents a main window with Save|Cancel|Apply buttons
2. ContentGrp1 is [m,v,c] and represents the main window content (there can be many content groups)

The design issue is when clicking "Save"(OK) or "Cancel" the actions need to be handled by the ContentGrp controller - not the parent controller. To solve this I used the event router publish facility to push the save, cancel events from the parent controller to the child controller e.g.

    @ArtifactProviderFor(GriffonController)
    class PreferencesController {
        void clickOK() {
            application.eventRouter.publishEvent('preferencesWin', ['OK'])
        }
        void clickCancel() {
            application.eventRouter.publishEvent('preferencesWin', ['Cancel'])
        }
        // default behaviour
        def cancel() {
            application.windowManager.hide('preferencesWin')
        }
    }

    @ArtifactProviderFor(GriffonController)
    class ContentController1 {
        PreferencesController parentController

        void mvcGroupInit(Map args) {
            // listen for the button events issued from the parent controller
            application.eventRouter.addEventListener('preferencesWin', { params ->
                switch (params[0]) {
                    case "OK":
                        eventOK()
                        break
                    case "Cancel":
                        eventCancel()
                        break
                }
            } as RunnableWithArgs)
        }

        def eventOK() { 
            println "OK..now save the model and close the window" 
            parentController.cancel()
        }
        def eventCancel() {
            parentController.cancel()
        }
    }

This works great the first time.  The problem starts after the 'preferencesGroup' is destroyed (along with the content group) and the window is then reopened and mvc groups recreated.  What I found is that 'parentController' of ContentController1 is null.  It turns out this is because ALL the previous controller instances are still referenced in the DefaultEventListener.functionalListeners map.

The Griffon Guide does not explicitly mention that it's necessary to remove custom event listeners but I think this would be the case.  It would be great if the mvcGroupDestroy could automatically remove any listeners referring to griffon artifacts in the process of being destroyed / dereferenced.

Cheers,

Paul

**Comment by aalmiray** [comment]
AFAIK controllers take down all listeners with them when destroyed. See https://github.com/griffon/griffon/blob/development/subprojects/griffon-core/src/main/java/org/codehaus/griffon/runtime/core/mvc/DefaultMVCGroupManager.java#L369-L374 which invokes https://github.com/griffon/griffon/blob/development/subprojects/griffon-core/src/main/java/org/codehaus/griffon/runtime/core/event/AbstractEventRouter.java#L380-L407 

There's the possibility of a bug in `AbstractEventRouter` that's preventing a `RunnableWithArgs` listener form being removed. In any case, this bug should not cause `parentController` to be set to null. There may be two unrelated issues here. Will have to investigate further.

**Comment by shnplr** [comment]
https://github.com/griffon/griffon/blob/development/subprojects/griffon-core/src/main/java/org/codehaus/griffon/runtime/core/event/AbstractEventRouter.java#L403-L407

Debugger shows:
listenerClass = "class com.sun.proxy.$Proxy22"
listener = SampleController$_mvcGroupInit_closure1@1f3e1e2

I think is returning false for groovy closure

**Comment by aalmiray** [comment]
Aha! This makes sense now. Thank you for doing the research. The fix then may be as simple as providing a `GroovyAwareDefaultEventRouter` with the correct implementation for `isNestedListener`. :smile:

**Comment by shnplr** [comment]
https://github.com/griffon/griffon/blob/development/subprojects/griffon-core/src/main/java/org/codehaus/griffon/runtime/core/mvc/DefaultMVCGroupManager.java#L407-L409

I think here is where parentController is set to null - I don't think it'd make sense to revive this artifact instance (due to the bug) as it shouldn't be there in the first place.
