### ISSUE TITLE
Lifecycle method documentation

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#117]
1. Typo in http links for mvcGroupInit() and mvcGroupDestroy lifecycle methods javadoc
e.g. s/GriffonMVCArtifact/GriffonMvcArtifact

2. Suggestion

Section 10.4 documents lifecycle events, but I didn't see a similar section which "lists" and describes lifecycle methods.  Suggest adding new section for lifecycle methods
e.g.
mvcGroupInit(Map)
mvcGroupDestroy()
others?

3. Suggestion

controllers.adoc (line 87)
"react to MVC initialization/destruction via a pair of methods (mvcGroupInit(), mvcGroupDestroy())."

should these be linked to javadoc url?

**Comment by aalmiray** [comment]
Suggestions 1 and 3 have been taken care of. Number 2 still pending
