### ISSUE TITLE
Possible race condition accessing parent* inside mvcGroupDestroy

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#118]
In some cases a NPE may be thrown when accessing parent* attributes within artifacts mvcGroupDestroy() lifecycle method; possibly due to Griffon framework explicitly setting parent* attributes to null on destroy.

For example: It's conceivable the artifact being destroyed wishes to access its parent* attributes on destroy - perhaps to deregister itself for a custom event.  The problem occurs if the code is sent to the event queue
e.g. 

    void mvcGroupDestroy() {
        runInsideUIAsync {
            parentController.myDeregisterEventMethod(this)  // <- NPE (parentController is null)
        }
    }

A possible workaround is to save a local reference:

    void mvcGroupDestroy() {
        def pc = parentController   // save reference to parentController
        runInsideUIAsync {
            pc.myDeregisterEventMethod(this)
        }
    }

The behaviour appears inconsistent with conventional attributes (model/view/controller/builder etc) which don't appear to be nulled.  Assuming there's a good reason to null parent* attributes, it could perhaps be solved by sending it to the event queue - assuming mvcGroupDestroy() has completed?

**Comment by aalmiray** [comment]
I'm afraid that the framework can't guarantee parent* references will not be null if the code is wrapped with `runInsideAsync`. Your approach is the right way to go.

**Comment by shnplr** [comment]
Yes that's fair enough - thanks for confirming the approach.  OK to close.
