### ISSUE TITLE
FileNotFoundException loading artifact from jar

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#122]
Using javafx gradle plugin a Windows MSI distribution installs in "C:\Program Files"
At runtime the following exception is reported:

[JavaFX-Launcher] WARN  griffon.util.ServiceLoaderUtils - An error occurred while loading resources from jar:file:/C:/Program%20Files/sampleapp/app/sampleapp-0.1.0.jar!/META-INF/griffon
java.io.FileNotFoundException: C:\Program%20Files\sampleapp\app\sampleapp-0.1.0.jar (The system cannot find the path specified)
	at griffon.util.ServiceLoaderUtils.handleJarResource(ServiceLoaderUtils.java:144)
	at griffon.util.ServiceLoaderUtils.load(ServiceLoaderUtils.java:110)
	at griffon.javafx.JavaFXGriffonApplication.init(JavaFXGriffonApplication.java:67)

perhaps...
    new JarFile(new File(url.toURI()))

**Comment by swalton00** [comment]
This looks like a standard Windows issue -- notice that the missing file is
"C:\Program%20Files". I'll bet the correct file name is "C:\Program Files"
This is what results when you pass in that type of file name to a URL fixer
(to make it legal. The the standard location in Windows is "Program Files".
That said, I'm not sure what the best approach is to fixing it. I usually
try to make make my path names have no spaces in them (by using the 8.3
name like PROGRA~1 -- see theese by doing a dir /x), but that doesn't fix
this issue. I suspect the best answer may be to no do the fixup on the file
name.

Scott Walton

On Mon, Nov 9, 2015 at 6:46 AM, shnplr <notifications@github.com> wrote:

> Using javafx gradle plugin a Windows MSI distribution installs in
> "C:\Program Files"
> At runtime the following exception is reported:
>
> [JavaFX-Launcher] WARN griffon.util.ServiceLoaderUtils - An error occurred
> while loading resources from
> jar:file:/C:/Program%20Files/sampleapp/app/sampleapp-0.1.0.jar!/META-INF/griffon
> java.io.FileNotFoundException:
> C:\Program%20Files\sampleapp\app\sampleapp-0.1.0.jar (The system cannot
> find the path specified)
> at
> griffon.util.ServiceLoaderUtils.handleJarResource(ServiceLoaderUtils.java:144)
> at griffon.util.ServiceLoaderUtils.load(ServiceLoaderUtils.java:110)
> at
> griffon.javafx.JavaFXGriffonApplication.init(JavaFXGriffonApplication.java:67)
>
> perhaps...
> new JarFile(new File(url.toURI()))
>
> to pass File() object to JarFile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/griffon/griffon/issues/122>.
>



-- 
Scott Walton

**Comment by shnplr** [comment]
Hi Scott,

This is true but perhaps using URI class instead of URL the ServiceLoaderUtils can resolve the correct file name instead of passing a URL encoded string to the JarFile constructor.

Cheers,
Paul

**Comment by swalton00** [comment]
That class can take a String. If it isn't encode at all, it should work.

On Tue, Nov 10, 2015 at 12:01 AM, shnplr <notifications@github.com> wrote:

> Hi Scott,
>
> This is true but perhaps using URI class instead of URL the
> ServiceLoaderUtils can resolve the correct file name instead of passing a
> URL encoded string to the JarFile constructor.
>
> Cheers,
> Paul
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/griffon/griffon/issues/122#issuecomment-155291457>.
>



-- 
Scott Walton

**Comment by aalmiray** [comment]
The thing is, the jar file is encoded along with the path, that is `jar:file:/C:/Program%20Files/sampleapp/app/sampleapp-0.1.0.jar!/META-INF/griffon`. The jar file is actually just `C:/Program%20Files/sampleapp/app/sampleapp-0.1.0.jar` so we have to parse the input to figure out the correct file. Using `url.toURI()` and supplying it directly to `new File()` will most likely result in a non-existing file. We have to strip `jar:file:/` and everything after `!` in order to find the right file.

**Comment by shnplr** [comment]
Would this work?

// OLD
            String u = url.toString();
            JarFile jar = new JarFile(u.substring(JAR_FILE_SCHEME.length(), u.length() - path.length() - 2));

// NEW
            JarURLConnection jarCon = (JarURLConnection) url.openConnection();
            URL jarUrl = jarCon.getJarFileURL();
            File file = new File(jarUrl.toURI());
            JarFile jar = new JarFile(file);

**Comment by shnplr** [comment]
Actually with JarURLConnection the code could simply be:

/ OLD
String u = url.toString();
JarFile jar = new JarFile(u.substring(JAR_FILE_SCHEME.length(), u.length() - path.length() - 2));

// NEW
JarURLConnection jarCon = (JarURLConnection) url.openConnection();
JarFile jar = jarCon.getJarFile();
