### ISSUE TITLE
Update latest guide URL to point to 2.5.0

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#127]
http://griffon-framework.org/guide/latest/ -> http://griffon-framework.org/guide/2.4.0/

**Comment by aalmiray** [comment]
The supplied link points to 2.5.0 already. Is there a page where this is not working?

**Comment by shnplr** [comment]
On this page:
http://griffon-framework.org/documentation.html

There is a link to:
The "Griffon Guide" is your first stop for documentation. It discusses all features available to Griffon applications.

The href for "Griffon Guide" is: http://griffon-framework.org/guide/latest/
which redirects to version 2.4.0

GET http://griffon-framework.org/guide/latest/ [HTTP/1.1 301 Moved Permanently 0ms]
GET http://griffon-framework.org/guide/2.4.0 [HTTP/1.1 302 Moved Temporarily 499ms]
GET http://griffon-framework.org/guide/2.4.0/ [HTTP/1.1 200 OK 0ms]

**Comment by aalmiray** [comment]
the link in question redirects to 2.5.0 for quite some time now :smile:

**Comment by shnplr** [comment]
You're right.  Seems FF caches the 301 so after clearing the cache it redirects correctly.  OK to close.
