### ISSUE TITLE
Provide documentation on how to configure checkstyle.

### ISSUE THREAD

**Issue by Richard-Cranium** [griffon/griffon#149]
Griffon 2.5.0

The griffon team does not appear to like tabs in source files.  Some of us do.
I get checkstyle errors when building a project via gradle and there is no indication on the griffon site
on how to stop that check.

**Comment by aalmiray** [comment]
Both the griffon build and projects generated with the standard lazybones templates use the core `checkstyle` plugin provided by Gradle. Its usage is documented at the Gradle docs site https://docs.gradle.org/current/userguide/checkstyle_plugin.html. This plugin provides just the means to run Checkstyle on all configured sourceSets; you'll have to look for specific rule configuration at the Checkstyle project site http://checkstyle.sourceforge.net/checks.html.

The Griffon build splits its build instructions into several build files, the one containing checkstyle (and other quality checks) is known as `code-quality.gradle` https://github.com/griffon/griffon/blob/development/build.gradle#L183 whose configuration is quite straight forward https://github.com/griffon/griffon/blob/development/gradle/code-quality.gradle#L23-L30

**Comment by Richard-Cranium** [comment]
Fair enough.  The "apply from" lines are rather explicit in the build.gradle file.
