### ISSUE TITLE
Netbeans view of griffon gradle projects is confusing at best.

### ISSUE THREAD

**Issue by Richard-Cranium** [griffon/griffon#152]
Preface:

Griffon 2.5.0

Netbeans treats maven and gradle projects as first-class citizens; I don't have to run anything to add Netbeans-specific files or metadata to create a Netbeans project.  With that in mind,  I don't expect you to provide a griffon-specific Netbeans plugin.  In fact, I don't think that should be necessary.

However, 

2. If I open a project that contains a pom.xml, Netbeans shows a "sane" view of the project.  Files in src/main/java are found in the source folders marked as [Java] and files in src/main/groovy are found in source folders marked as [Groovy].
3. If I open other random gradle projects in Netbeans, I get a "sane" view of the project, as mentioned above.
4. If I open a griffon project that has only a build.gradle in Netbeans, I get a not-sane view of the project.  For example, the same set of files that are shown in "Source Packages [Groovy]" are also shown in "Source Packages [Java]", despite there being absolutely no groovy source files in the project whatsoever.
5. Oddly, the Test Packages are shown correctly.  "Test Packages [Groovy]" is empty, since I have no tests written in groovy.  "Test Packages [Java]" contain a reference to the java tests that I have.

This is fairly easy to re-create.  Create a griffon-javafx-java project, remove/rename the project's pom.xml file, and open the project in Netbeans 8.1.  Run a priming build (if Netbeans doesn't do it for you).

**Comment by aalmiray** [comment]
I think this may be a NetBeans issue, related to its Gradle support. The generated build file applies the `groovy` plugin but disables Groovy compilation for main sources by defining the following line (around line 80)

    compileGroovy.enabled = false

Methinks NetBeans' Gradle support may be ignoring this option altogether. Both IntelliJ and Eclipse display the correct project structure. There are no specific settings in IntelliJ nor Eclipse to enable such project structure.

**Comment by Richard-Cranium** [comment]
OK, fair enough.  I'll raise the issue over there.  Thanks!

**Comment by MarceloRuiz** [comment]
People having this issue can read the following thread in **griffon-user**:

[http://griffon-user.74797.x6.nabble.com/Some-problems-with-NetBeans-and-Griffon-td215.html](url)
