### ISSUE TITLE
editor-javafx-java : error on quit

### ISSUE THREAD

**Issue by myteer** [griffon/griffon#153]
## 3 : do quit, but not normal exit
![2](https://cloud.githubusercontent.com/assets/9781523/14208719/5b0b5890-f853-11e5-87f1-b455d622d8c0.png)
## 4 : thread  always on running！ 
![3](https://cloud.githubusercontent.com/assets/9781523/14208739/7721eef4-f853-11e5-96da-c84a071dedc9.png)

**Comment by myteer** [comment]
`@Threading(Threading.Policy.INSIDE_UITHREAD_SYNC)
    public void quit() {
        getApplication().shutdown();
    }`
**With that annotation,quit is OK!  do I have to shutdown Application with INSIDE_UITHREAD_SYNC ?**

**Comment by aalmiray** [comment]
I'd expect the shutdown sequence to be executed in a thread that's not the UI thread. Perhaps JavaFx has a special requirement when shutting down and closing the last/primary Stage?

**Comment by myteer** [comment]
But do you know the reason why not normal exit, is the thread lock?
Can you reproduce the problem?
How should I solve this problem?
before call shutdown()，should i destory other mvcGroup by myself ?

**Comment by myteer** [comment]
sorry for trouble you with some simple question, I'm a new griffoner

**Comment by aalmiray** [comment]
I have not tried running the application yet. could you also give us more details about your setup? You'll notice a few logging statements when the application starts, the first ones contain information such as Griffon version, JVM and OS. Those details would be very helpful.

It looks to me that a good workaround so far is what you just tried, wrapping the shutdown call so that it gets executed inside the UI thread. You don't have to explicitly destroy MVC groups as the Griffon runtime will take care of that for you.

**Comment by myteer** [comment]
**development environment is as follows:**
```
[2016-04-05 09:15:50,412] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Griffon 2.6.0
[2016-04-05 09:15:50,413] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Build: 2016-03-04T09:20:04.661+0200
[2016-04-05 09:15:50,413] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Revision: c28a7fa9ea7bf8f5b658ddf11d64c4f30fea5c05
[2016-04-05 09:15:50,413] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - JVM: 1.8.0_66 (Oracle Corporation 25.66-b18)
[2016-04-05 09:15:50,413] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - OS: Windows 10 10.0 amd64
```
**I debug it, it seems like that the ContainerView can't be destroyed in UI thread, submit task with `Platform.runLater(task)` ,but can't return result with` task.get()`, I don't know why.**

**All debugging information is in the following log file:**
[log.txt](https://github.com/griffon/griffon/files/203694/log.txt)

**Comment by myteer** [comment]
@aalmiray 
**It may be a bug, I created a javafx class to test as follow:**

```
public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        Button testBtn = new Button("test");
        Thread uiThread = Thread.currentThread(); //(1)
        testBtn.setOnAction(event -> {
            stage.hide(); //(2)
            new Thread(() -> {
                System.out.println(Thread.currentThread().getName() + ":--start--");
                FutureTask<Void> task = new FutureTask<Void>(() -> {
                    System.out.println(Thread.currentThread().getName() + ":--test task--");
                }, null);
                try {
                    Thread.sleep(1000);//(3)
                    System.out.println(uiThread.isAlive());//(4)
                    Platform.runLater(task);//(5)
                    task.get(5, TimeUnit.SECONDS);//(6)
                    System.out.println(Thread.currentThread().getName() + ":--end--");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }).start();
        });

        stage.setScene(new Scene(new StackPane(testBtn), 400, 300));
        stage.show();
    }
}
```
**(1)hold a ui thread to determine if it is alive
(2)hide stage, this will cause the ui thread to die
(3)wait a moment to make sure the ui thread is died
(4)show whether the ui thread is alive or not
(5)submit task with `Platform.runLater(task)` to run task in ui thread
(6)waiting for task return**

**the result as follow:**
![11](https://cloud.githubusercontent.com/assets/9781523/14352558/b83d044c-fd07-11e5-999d-bfc845fae7ce.png)

**so after stage hide, it's wrong to submit task with `Platform.runLater(task)` and call `task.get()`; 
the reason in `com.sun.javafx.application.PlatformImpl` as follow:**
![2](https://cloud.githubusercontent.com/assets/9781523/14353027/d0b1fe7c-fd09-11e5-873b-94ffcc71880e.png)

**the griffon's `shutdown()` in `griffon.javafx.AbstractJavaFXGriffonApplication`：**
`Shutdown stage 2: notify all shutdown handlers` will hide the stage
`Shutdown stage 3: destroy all MVC groups` will destroy `GriffonView` with `runInsideUISync`
**so the griffon application can’t normally exit**

**Comment by shnplr** [comment]
what happens if you invoke close() method on the javafx.stage.Stage, instead of shutdown()?

**Comment by myteer** [comment]
@shnplr 
```
    @Threading(Threading.Policy.INSIDE_UITHREAD_ASYNC)
    public void quit() {
       // getApplication().shutdown();
        getApplication().getWindowManager().getWindows().forEach(window -> {
            ((Stage)window).close();
        });
    }
```
invoke stage.close() must run in UI thread， same as invoke application.shutdown() in UI thread.
