### ISSUE TITLE
Griffon javafx plugin support for groovyfx 8

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#154]
To replace groovyfx-0.4.0 with groovyfx-8.0.0 my gradle config is:

	dependencies {
		compile("org.codehaus.griffon:griffon-javafx-groovy:${griffon.version}") {
			exclude group: 'org.codehaus.groovyfx', module: 'groovyfx'
		}
		compile 'org.groovyfx:groovyfx:8.0.0'
	}

	configurations {
		all*.exclude group: 'org.codehaus.groovyfx', module: 'groovyfx'
	}

**Comment by aalmiray** [comment]
Fixed with https://github.com/griffon/griffon/commit/dc442a95b9967f628050bf1628a5bc22fd3f7172
