### ISSUE TITLE
CompositeBuilder ignores the disabled flag (javafx toolkit)

### ISSUE THREAD

**Issue by stenis999** [griffon/griffon#156]
Using: Griffon 2.6.0 with javafx toolkit.

This is just a minor issue with a simple workaround.

It looks like the CompositeBuilder ignores the 'disabled' flag (at least for textfields - I have not tested any other type of nodes).

Sample initUI method for the view:

    void initUI() {
        builder.application(title: 'Just a test', sizeToScene: true, centerOnScreen: true) {
            scene {
                vbox(padding: 5) {
                    textField(id: 'myTextField', text: 'I should be disabled', disabled: true)
                }
            }
        }
        // This line has to be uncommented for the field to be disabled initially
        //builder.myTextField.disabled = true
    }

If the last line is uncommented, it works fine. 

I also noted that if the "vbox" is removed (i.e. the textField is the only node in the scene), then the field is actually disabled. When it is inside a vbox, it is not.

**Comment by aalmiray** [comment]
Hmm this could be an issue in GroovyFX too. Will have to check on both places. Thank you for the report!

**Comment by aalmiray** [comment]
The property name is actually `disable` instead of `disabled`. This is an unfortunate naming problem found in the JavaFX APIs that we can't change.

**Comment by stenis999** [comment]
Ah... nice catch. Changing to "disable" works fine.
