### ISSUE TITLE
Use Java 8 in griffon-core?

### ISSUE THREAD

**Issue by khatchad** [griffon/griffon#167]
I noticed that griffon-core is using Java 7 while other modules are using Java 8. Is it possible to use Java 8 in griffon-core?

**Comment by aalmiray** [comment]
Possible? Yes. Recommended? No. Griffon is designed to support multiple toolkits, other than JavaFX. It's also designed to support migrations from legacy designs without forcing a move to the most recent JDK releases. There's an additional module named `griffon-core-java8` that delivers additional features that target JDK8+.

**Comment by khatchad** [comment]
Thank you, @aalmiray. I was going to issue a PR similar to https://github.com/aalmiray/jsilhouette/pull/1 but many of the refactorings took place in `griffon-core` but I held off since it's not 1.8 compatible.
