### ISSUE TITLE
Please generate compiled code with all debugging info enabled

### ISSUE THREAD

**Issue by MarceloRuiz** [griffon/griffon#171]
When learning the platform is really useful to have all the debugging information enabled, including local variables.

**Comment by aalmiray** [comment]
This would bloat the binaries for production. An alternative would be to link the `-source` and `-javadoc` JARs for each Griffon dependency.

**Comment by MarceloRuiz** [comment]
I downloaded the source code from griffon-master to build the project myself and add the dependencies as files to experiment with the framework. Could you please tell me what to change in the build files to compile with full debug info?
Thanks

**Comment by aalmiray** [comment]
I believe this is what you need

	tasks.withType(JavaCompile) {
	    options.debug = true
	}

See https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html for more info

**Comment by MarceloRuiz** [comment]
Thanks!

**Comment by MarceloRuiz** [comment]
Andres, I was thinking about this issue and it is true that slim binaries are preferred for production, and I think you would agree that having complete debugging info available during learning, debugging and -maybe- testing is valuable for programmers. Wouldn't be great if the Griffon's build could produce the actual version of the binaries for production and also a version for debugging so developers could quickly switch between them as needed?  (for example, producing both **griffon-core** and **griffon-core-dbg**).
