### ISSUE TITLE
build scripts don't work with gradle 3.1

### ISSUE THREAD

**Issue by rburgst** [griffon/griffon#173]
everything works fine with 2.14 but not with 3.0 or 3.1

```
~/Development/gradle-3.1/bin/gradle run

FAILURE: Build failed with an exception.

* Where:
Script '/Users/rainer/Documents/workspaces/privat/opensource/test2/gradle/package.gradle' line: 10

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'installApp' for root project 'test-2' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.239 secs
``` 

Repro steps

1. create a new project with `lazybones create griffon-javafx-groovy test2`
2. try to build with gradle 3.1

**Comment by aalmiray** [comment]
Gradle 3.0 changed some of the public tasks previously exposed. https://docs.gradle.org/3.0/release-notes#changes-to-previously-deprecated-apis

* The installApp task is no longer created by the application plugin (use `installDist` instead).

Will update project templates for the upcoming `2.8.0` release, however you'll have to manually s/installApp/installDist/ if running Gradle 3+.
