### ISSUE TITLE
Cannot find a template named 'griffon-javafx-java'. Project has not been created.

### ISSUE THREAD

**Issue by PhlegmaBoy** [griffon/griffon#175]
While ....Available templates in griffon/griffon-lazybones-templates

```
griffon-javafx-groovy
griffon-javafx-java
griffon-javafx-kotlin
griffon-lanterna-groovy
griffon-lanterna-java
griffon-pivot-groovy
griffon-pivot-java
griffon-plugin
griffon-swing-groovy
griffon-swing-java
```

**Comment by aalmiray** [comment]
Could you tell us a bit more about your environment and setup, such as:
 - Which operating system are you using?
 - What version of Lazybones did you try?
 - Do you get a full list of griffon templates when invoking `lazybones list`?

Just wanted to check the instructions laid out at http://griffon-framework.org/ are accurate.

**Comment by PhlegmaBoy** [comment]
I'm using Linux  , Ubuntu 2016.04 Debian distribution.
Lazybones version 0.8.3
I'm getting a bunch of lists divided into two groups:Available templates in pledbrook/lazybones-templates and Available templates in griffon/griffon-lazybones-templates.
I repeated the instructions given on the website four times but still get the same problem.

**Comment by aalmiray** [comment]
I see. Are there any griffon templates available in `~/.lazybones/templates`? Do you encounter a similar problem with other lazybones templates such as `gradle-quickstart`?

**Comment by PhlegmaBoy** [comment]
My .lazybones directory doesnt have have the templates directory only the config.groovy that I created manually. I also tried with quicstart but getting the same error message.

**Comment by aalmiray** [comment]
This sounds like a problem in Lazybones itself. Could you try downloading the template directly from https://bintray.com/griffon/griffon-lazybones-templates/griffon-javafx-java-template/1.8.0? Place it under `~/.lazybones/templates`. Be sure to rename it to `griffon-javafx-java-1.8.0.zip`.

**Comment by PhlegmaBoy** [comment]
Problem Solved ! Thank You.

**Comment by aalmiray** [comment]
what was the cause of the problem?
