### ISSUE TITLE
Artifact template name is not constraint

### ISSUE THREAD

**Issue by AbdelRahmaneB** [griffon/griffon#176]
When you create a new artifact without specifying a template, you are given some choices, the script do not validate the choices

**Comment by aalmiray** [comment]
Here's the faulty code https://github.com/griffon/griffon/blob/development/templates/griffon-javafx-java-templates/templates/subtmpl-artifact/lazybones.groovy#L22-L24

The loop should validate that the input is inside the list of `templateNames`.

**Comment by AbdelRahmaneB** [comment]
Get it, i'll fix it :)

**Comment by aalmiray** [comment]
Fixed with #177
