### ISSUE TITLE
Latest application-master-pom is empty

### ISSUE THREAD

**Issue by AlexanderZobkov** [griffon/griffon#200]
The freshly generated project from a lazybone template griffon-swing-groovy can't be complied with Maven due to POM application-master-pom:1.9.1 is nearly empty and does not contains expected dependencies and plugins declarations. 

In addition, a reference to application-master-pom in griffon user documention is broken. See section 15.4.

**Comment by aalmiray** [comment]
I've uploaded the correct application-master-pom-1.9.1.pom to bintray. Please try again.
Thank you for letting us know the file was incorrect 😄
