### ISSUE TITLE
RuntimeException in initUI method of AbstractJavaFXGriffonView should shutdown griffon

### ISSUE THREAD

**Issue by MarceloRuiz** [griffon/griffon#208]
Hi, 
I think if for some reason a view could not be loaded and displayed, and an RuntimeException in 
`public void initUI(){...}`
 is thrown, Griffon should stop its execution, thus preventing as a zombie thread running forever.
Thanks

**Comment by aalmiray** [comment]
The exception is caught by the `ExceptionHandler` and sent as an event through the application's `EventRouter`, as the exception occurs inside the UI thread. You may register an exception handler for this exception.

What could be done on the Griffon side is to wrap the exception into a more specific one, such as `GriffonViewIntializationException`. This will make it easier for developers to match against when using an event handler.
