### ISSUE TITLE
Testing Entire Application

### ISSUE THREAD

**Issue by Jeredriq** [griffon/griffon#234]
Can i test an entire application using griffon? And if i can, is there any documentation? Because i've been searching for crazy and couldnt found anything about application under test with griffon.

**Comment by aalmiray** [comment]
Yes, you can test an application at many different levels: unit, integration, and functional. The Griffon Guide describes how to get started with unit & integration testing

    http://griffon-framework.org/guide/2.10.0/#_testing

The MVC patterns tutorial applications (described at http://griffon-framework.org/tutorials/5_mvc_patterns.html) also have unit, integration, and functional tests, for example https://github.com/griffon/griffon/blob/development/tutorials/patterns/pmvc/src/functional-test/java/org/example/SampleFunctionalTest.java

**Comment by Jeredriq** [comment]
Thank you so much:D
