### ISSUE TITLE
Griffon on Maven Central

### ISSUE THREAD

**Issue by allquixotic** [griffon/griffon#237]
Would it be possible to upload a copy of Griffon to Maven Central? I'm dealing with an internal Nexus repository that pulls from Maven Central, but not Bintray, so with the current Griffon Framework we are not able to easily obtain it using Maven or Gradle.

**Comment by aalmiray** [comment]
All Griffon binaries are linked to JCenter as far as I recall, including plugin releases. See https://bintray.com/griffon/griffon/griffon-core for example. Now, publishing to Maven Central might require a name change in packages as MC has strict rules regarding package ownership. Will have to review the case with the MC admins.

**Comment by aalmiray** [comment]
Filed https://issues.sonatype.org/browse/OSSRH-32458

**Comment by allquixotic** [comment]
Awesome, thank you! Do you / Griffon as a whole accept donations? We're looking to use this in a small in-house line of business app at my place of work but I might drop a personal tip because this will save me a lot of headache if it turns out to be half as useful as it seems from the docs and tutorials. :)

**Comment by aalmiray** [comment]
All Griffon 2.11.0 are now available at Maven Central. See https://oss.sonatype.org/content/groups/public/org/codehaus/griffon/
It will take me a few days to publish all Griffon plugins as the currently generated POMs for these artifacts do not meet the requirements set forth by Maven Central, so please bear with us 😅

**Comment by aalmiray** [comment]
@allquixotic: thank you for thinking in making a donation, would a setup such as Patreon work for you?

**Comment by allquixotic** [comment]
Patreon works fine for me! :) +1

**Comment by aalmiray** [comment]
Alright, you can find the Patreon page at https://www.patreon.com/user?u=6609318 😄

**Comment by aalmiray** [comment]
Do let me know if you need additional artifacts posted to Maven Central. It'll take some extra effort to publish any plugins (http://griffon-framework.org/plugins.html) to MC as the gradle-build-plugin requires some more work (see #238) but a manual update is possible.

**Comment by allquixotic** [comment]
I would appreciate the griffon-configuration-plugin and griffon-swingx-plugin on MC, but it's not urgent. Thank you!

**Comment by aalmiray** [comment]
`griffon-swingx 1.1.1` is already available from MC (https://search.maven.org/#search%7Cga%7C1%7Cgriffon-swingx). `griffon-configuratoin 1.0.1` was synced just a few minutes ago; it'll take from a few minutes to a couple of hours for all artifacts to be fully available.
