### ISSUE TITLE
Maven issues with both windows and linux

### ISSUE THREAD

**Issue by swalton00** [griffon/griffon#242]
Attempting to build using Maven from a clean, unmodified newly created Griffon on both Linux (Ubuntu) and windows results in a failure of an ant task: 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.627 s
[INFO] Finished at: 2017-07-06T10:54:19-04:00
[INFO] Final Memory: 22M/179M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (process-resources) on project pivgr
ov: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] C:\Projects\bookTest\pivgrov\maven\process-resources.xml:9: The following error occurred while executing this li
ne:
[ERROR] C:\Projects\bookTest\pivgrov\maven\ant-macros.xml:6: C:\Projects\bookTest\pivgrov\src\main\resources does not ex
ist.
[ERROR] around Ant part ...<ant antfile="maven/process-resources.xml"/>... @ 4:47 in C:\Projects\bookTest\pivgrov\target
\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]

The build is successful if run using gradle. There are also several Maven warnings:

[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.spw:pivgrov:jar:1.0
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as rep
ortPlugins parameter.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by aalmiray** [comment]
According to the error it looks like `src/main/resources` is missing. The project should have the right structure if it was created using a Lazybones template.

**Comment by swalton00** [comment]
The project was created by a lazybones template.  It doesn't seem to happen if the build is first done with gradle (Maven succeeds after that). To recreate, create a new griffon project with lazybones and then (without any intervening steps) attempt the build with Maven. I saw the same issues on both Ubuntu (tools installed with SDKman, and Windows with tools installed manually or with posh-gvm).

**Comment by swalton00** [comment]
Did some additional testing. The templates don't create "src/main/resources" Maven fails because it doesn't exist. The first Gradle build silently creates it. Thereafter all the Maven builds also succeed. The builds were all done immediately after creating a fresh project from the latest templates (without any modification at all).

I believe this to be a bug in the templates.

**Comment by aalmiray** [comment]
I see. Gradle creates all necessary directories on the first run, however Maven can't be taught to do that. The alternative may be to create the directory as part of the lazybones script. I like this idea better than adding an empty, hidden file such as "src/main/resources/.retain" to the templates
