### ISSUE TITLE
StringIndexOutOfBoundsException with Java 9

### ISSUE THREAD

**Issue by tschulte** [griffon/griffon#263]
Java 9 reports java.version as "9". This results in a `StringIndexOutOfBoundsException: begin 0, end 3, length 1` in `griffon.util.GriffonApplicationUtils` in line 266.

```java
        javaVersion = System.getProperty("java.version"); // => "9"
        String version = javaVersion.substring(0, 3); // => StringIndexOutOfBoundsException
```

**Comment by aalmiray** [comment]
Sorry, I acted too fast to solve this issue and did not notice you had an incoming PR 😢

**Comment by tschulte** [comment]
No problem.

**Comment by tschulte** [comment]
When will you release 2.13.0?

**Comment by aalmiray** [comment]
Current schedule is set to December 1st 2017. Do you need an earlier release?

**Comment by tschulte** [comment]
We need a version that works with Java 9. But I can also build our own special-version and deploy that to our nexus.
