### ISSUE TITLE
Routing between two views

### ISSUE THREAD

**Issue by serzh-f** [griffon/griffon#271]
Hi aalmiray! I have a problem. Can you help me? 

How can I change current view to another and init events for new view?
I use JavaFX. 

Look at screen

Thank you.

![b5295e599c](https://user-images.githubusercontent.com/5091646/31170117-9aa32cd2-a903-11e7-987f-2e38e2edb205.jpg)

**Comment by aalmiray** [comment]
If I understood you correctly, you want the main content area to change when a button is clicked. You can follow a similar approach as the one shown http://griffon-framework.org/tutorials/4_javafx_views.html. I'd use a `NamedCardPane` or an `IndexedCardPane` to manage the content area. Those two widgets are part of Griffon's JavaFX layout support.
