### ISSUE TITLE
Lazybones create project need include .gitignore file

### ISSUE THREAD

**Issue by netroby** [griffon/griffon#274]
please add .gitignore file for lazybones create project template.

**Comment by aalmiray** [comment]
Any particular contents that this file should have?

**Comment by netroby** [comment]
Add the file / dir list should not include in the git repository.

like build/

**Comment by aalmiray** [comment]
VCS files will not be included in templates, for the same reason as explicit IDE files (IntelliJ, Eclipse, NetBeans) are not included. It's best to leave these files to be created by the developer when needed.
