### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by sunyuyangg555** [griffon/griffon#276]
I have download this project , but I can not exec `gradle build`,

A problem occurred evaluating root project 'griffon'.
> A problem occurred configuring project ':application-master-pom'.
   > No .git directory found!`

 what should I do?

**Comment by sunyuyangg555** [comment]
Thank you very much for your reply! I use gradle 4.1, I will test with Gradle wrapper.

**Comment by aalmiray** [comment]
Any updates on this issue?

**Comment by sunyuyangg555** [comment]
I am sorry to reply now! I have builded on ubuntu.
