### ISSUE TITLE
How do I use the griffon-lookandfeel-plugin to give my app the napkin laf?

### ISSUE THREAD

**Issue by spierepf** [griffon/griffon#280]
I've followed the steps at: http://griffon-plugins.github.io/griffon-lookandfeel-plugin/#_maven

to configure my maven build to add the plugin to my build, and the napkinlaf:

https://mvnrepository.com/artifact/net.sf.squirrel-sql.thirdparty-non-maven/napkinlaf

Then I tried adding entries to `griffon-app/conf/Config.groovy`

`    lookandfeel.handler = 'Napkin'`
`    lookandfeel.theme = 'Napkin'`

But I still got the nimbus look and feel.

**Comment by aalmiray** [comment]
I see that the guide has an error on the groupIds however you should be able to get NapkinLaF to work by adding the following entries to your POM

        <dependency>
            <groupId>org.codehaus.griffon.plugins</groupId>
            <artifactId>lookandfeel-core</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.codehaus.griffon.plugins</groupId>
            <artifactId>griffon-lookandfeel-napkin</artifactId>
            <version>2.0.0</version>
        </dependency>

**Comment by spierepf** [comment]
To be sure that I followed the directions correctly, here is a diff:

```
$ git diff
diff --git a/griffon-app/conf/Config.groovy b/griffon-app/conf/Config.groovy
index b0c9a63..320147e 100644
--- a/griffon-app/conf/Config.groovy
+++ b/griffon-app/conf/Config.groovy
@@ -2,6 +2,8 @@ application {
     title = 'scheduler'
     startupGroups = ['app']
     autoShutdown = true
+    lookandfeel.handler = 'Napkin'
+    lookandfeel.theme = 'Napkin'
 }
 mvcGroups {
     // MVC Group for "app"
diff --git a/pom.xml b/pom.xml
index bfbe45a..c944b4e 100644
--- a/pom.xml
+++ b/pom.xml
@@ -35,7 +35,32 @@
         </plugins>
     </build>
 
+    <dependencyManagement>
+        <dependencies>
+            <dependency>
+                <groupId>org.codehaus.griffon.plugins</groupId>
+                <artifactId>griffon-lookandfeel-plugin</artifactId>
+                <version>2.0.0</version>
+                <type>pom</type>
+                <scope>import</scope>
+            </dependency>
+        </dependencies>
+    </dependencyManagement>
+
     <dependencies>
+        <dependency>
+            <groupId>org.codehaus.griffon.plugins</groupId>
+            <artifactId>griffon-lookandfeel-core</artifactId>
+            <version>2.0.0</version>
+        </dependency>
+
+        <dependency>
+            <groupId>org.codehaus.griffon.plugins</groupId>
+            <artifactId>griffon-lookandfeel-napkin</artifactId>
+            <version>2.0.0</version>
+        </dependency>
+
+        <!-- additional dependencies -->
         <!-- compile -->
         <dependency>
             <groupId>org.codehaus.groovy</groupId>

```

However, I am still getting the nimbus look-and-feel.

**Comment by aalmiray** [comment]
I've setup a sample application at https://github.com/aalmiray/sample-swing-groovy with both Maven and Gradle configuration. Perhaps this can serve as a starting point 😄

**Comment by spierepf** [comment]
I put the config stuff in the wrong place. I had it inside the application block instead of outside. :man_facepalming: 

Thanks again!
