### ISSUE TITLE
lazybones griffon-javafx-java gradle build fails on Windows because of failed unit test

### ISSUE THREAD

**Issue by steinmartin** [griffon/griffon#282]
Executing a gradle build on a just created lazybones griffon-javafx-java template fails because of unit test failure on Windows 7, Griffon 2.14.0 and 2.13.0, Java SE 1.8.0_162-b12.
The same procedure on Debian Stretch, Griffon 2.14.0, Java SE 1.8.0_151 does build well. The following shows the log from the Windows 7 system:  
```java
org.example.SampleJavafxJavaControllerTest > executeClickAction FAILED
    org.junit.ComparisonFailure at SampleJavafxJavaControllerTest.java:41

1 test completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.
```
Unit test ```SampleJavafxJavaControllerTest``` does not seem to wait
until controller method is executed. See the comments after the ```//``` line comments.

```java
@Test
public void executeClickAction() {
    // given:
    SampleJavafxJavaModel model = artifactManager.newInstance(SampleJavafxJavaModel.class);
    controller.setModel(model);
    // when:
    controller.invokeAction("click");
    await().atMost(2, SECONDS);  // seems to do nothing at all
    // then:
    assertEquals("1", model.getClickCount());  // code is executed before controller.click() method returns
}
```
If the code line ```await().atMost(2, SECONDS);``` is changed to ```await().atMost(2, SECONDS).until(() -> model.getClickCount(), notNullValue());```,
the test succeeds. Griffon and Awaitility is new for me, so **do not take this as a fix**!
I have no idea what really happens.

**Comment by steinmartin** [comment]
Forgot to mention that the code line from above:
```await().atMost(2, SECONDS).until(() -> model.getClickCount(), notNullValue())```
needs
```import static org.hamcrest.core.IsNull.notNullValue; ```

**Comment by aalmiray** [comment]
@steinmartin you are correct, the generated code does not have a condition and thus continues. Your suggestion works. It could also be changed to check for an integer value bigger than 0.
