### ISSUE TITLE
Recommended place to ask for help ?

### ISSUE THREAD

**Issue by mnellemann** [griffon/griffon#304]
Hey,

Is there an official place/list/slack to go to when in need of help ?

Specifically looking for information on how to use the slider (w. Groovy dsl) and bind to a controller method or model property when the slider value is changing. 

Br,
Mark

**Comment by aalmiray** [comment]
There's a mailing list available at http://griffon-user.74797.x6.nabble.com/
We also have a Gitter channel https://gitter.im/griffon/griffon

**Comment by mnellemann** [comment]
Thanks :)
For some reason I didn't find the info on the website.
