### ISSUE TITLE
Question - Using Griffon Services in other class

### ISSUE THREAD

**Issue by bytecod3r** [griffon/griffon#308]
Is there anyway to use the services that created in /services folder, from other class that are not part of griffon MCV?
 
e.g.
```
public class TestClass {
    @Inject
    private UIService uiService;
```

at the moment, the above throwing NPE.

**Comment by aalmiray** [comment]
Yes, as long as the consumer class participates in dependency injection. Either
1. The application has a `Module` where the target class is bound.
2. Pass a reference of the `Injector` to an instance of the target class and manually trigger injection of dependencies on it. This means you can't use constructor injector.

**Comment by bytecod3r** [comment]
thanks @aalmiray
