### ISSUE TITLE
FXObservable does not work

### ISSUE THREAD

**Issue by bytecod3r** [griffon/griffon#309]
Hi,

I was trying to use the @FXObservable for a string variable, but it seems it does not work propertly. It convert convert the variable test from String to StringProperty. Is there anything I am missing?

```
 @FXObservable
    String test;

@ControllerAction
    @Threading (Threading.Policy.INSIDE_UITHREAD_ASYNC)
    public void testing() {
        System.out.println(test);
    }

```

**Comment by aalmiray** [comment]
That's exactly what must happen. `String` is a plain type that has no knowledge of change events, while `StringProperty` does. All types annotated with `@FXObservable` are upgraded to their matching JavaFX property type.

**Comment by bytecod3r** [comment]
Thanks, Sorry I did not fully underestand your response.
In conclusion, how can I use the @FXObservable?

**Comment by aalmiray** [comment]
You would use annotated properties just like any other JavaFX observable property. The annotation is a convenience for writing the set of methods that expose the property, such as 

- `get<property>()`: returns the plain value.
- `set<property>()`: sets the plain value, triggers change events.
- `<property>Property()`: gives you direct access to the JavaFX observable

Thus you would call `testProperty().bind(...)` or pass `testProperty()` to any other piece of code that requires a JavaFX observable property.

One more thing, it's recommended that properties (state) be placed in the Model class, not in the Controller.

**Comment by bytecod3r** [comment]
![image](https://user-images.githubusercontent.com/8350933/94373798-4a3a5580-013a-11eb-8693-d83d904f596f.png)

Is this what you are referring to? the testProperty does not exists.

**Comment by aalmiray** [comment]
I'm afraid not. The Griffon project includes samples that showcase the use of several features. Here's one application that relies on `@FXObservable` to create 2 observable properties: `input` and `output`.

These properties are defined in the Model class

https://github.com/griffon/griffon/blob/development/samples/sample-javafx-groovy/griffon-app/models/sample/javafx/groovy/SampleModel.groovy

The Controller makes use of the plain type accessors to get and set the value, independent of JavaFX types

https://github.com/griffon/griffon/blob/development/samples/sample-javafx-groovy/griffon-app/controllers/sample/javafx/groovy/SampleController.groovy

Finally, the View binds the observable properties using standard JavaFX bindings

https://github.com/griffon/griffon/blob/development/samples/sample-javafx-groovy/griffon-app/views/sample/javafx/groovy/SampleView.groovy

both `inputProperty()` and `outputProperty()` methods are generated by the FXObservableASTTransformation. For this to work you must have `griffon-groovy-compile-x.x.x.jar` in the `compileOnly` configuration (Gradle) or in the `provided` scope (Maven).

**Comment by bytecod3r** [comment]
Thanks for responding so quickly

I have the groovy-compile in my gradle

![image](https://user-images.githubusercontent.com/8350933/94374375-735ce500-013e-11eb-9da6-c6b023d4c23e.png)


This is my Model:
![image](https://user-images.githubusercontent.com/8350933/94374395-8a033c00-013e-11eb-9fb8-53f70646086f.png)

This is my View:
![image](https://user-images.githubusercontent.com/8350933/94374403-9d160c00-013e-11eb-9318-73dc30beebf4.png)

by the way, my code is fully in java. I gonna stop bothing you after this if I cant get this work...

Thank you, as always very helpful

**Comment by aalmiray** [comment]
Ah that's it. AST transformations only work with Groovy code, not Java. `@FXObservable` is a Groovy AST transformation.

**Comment by bytecod3r** [comment]
ahh sad :(  Thank you.
