### ISSUE TITLE
There is no way to create new Griffon projects.

### ISSUE THREAD

**Issue by Richard-Cranium** [griffon/griffon#313]
Lazybones is dead; the skeletor replacement still isn't working.  What mechanism can new users use to create a new project?

**Comment by aalmiray** [comment]
You can use the Maven archetypes (which only create Maven projects) or bootstrap a project manually.

**Comment by Richard-Cranium** [comment]
Indeed.  I just read the documentation more closely from home and logged into here to say that very thing!
