### ISSUE TITLE
Griffon with Java on JDK 11 fails to run (NoClassDefFoundError: javax/annotation/PostConstruct)

### ISSUE THREAD

**Issue by swalton00** [griffon/griffon#317]
Using Griffon 2.16.0 on a brand-new project (Griffon, Swing, Java) on Windows 10, it successfully compiles with both JDK8 and JDK11. It will run on JDK8, but fails with java.lang.NoClassDefFoundError: javax/annotation/PostConstruct when run on JDK11 Java HotSpot 11.0.13

I understand that the javax.annotations package was deprecated in JDK 9 and removed in 11.

This was a clean install, with no files modified (getting ready to move a project to Java11).

**Comment by aalmiray** [comment]
You'll have to add the missing classes provided by the javax-annotation-api dependency https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api/1.3.2

**Comment by swalton00** [comment]
It now runs, but I do get an Exception: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel

It runs through, despite the exception. There is also the nasty warning about illegal reflective access (I see this with Groovy also):
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/jsw/.m2/repository/com/google/inject/guice/4.2.0/guice-4.2.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

**Comment by swalton00** [comment]
the NimbusLookAndFeel changed to javax.swing.plaf.nimbus.NimbusLookAndFeel
