### ISSUE TITLE
Hibernate4 and Mybatis plugins don't honor Hibernate4Aware or MybatisAware

### ISSUE THREAD

**Issue by swalton00** [griffon/griffon#47]
The mybatisHandler (or hibernate4Handler) are not injected unless the class is either a Controller or a Service. Simply annotating the class with either MybatisAware or Hibernate4Aware leaves the Handler as a null reference. The first use then fails. Changing the code to run as a Griffon Service solves that issue.

I'm not sure that simply annotating it will work because of the need for default Constructor (which gets invoked BEFORE the injection takes place, so references in the constructor will fail). If that is the case, then the documentation needs to be updated.

**Comment by aalmiray** [comment]
References to injected members (those annotated with @javax.inject.Inject) inside a constructor will always fail. You must use a method annotated with @javax.annotation.PostConstruct as initializer in order to grab hold of injected references.

The following controller code has been tested to work with Griffon 2.1.0, mybatis-plugin 1.1.0 and datasource-plugin 1.1.0

    package org.example

    import griffon.core.artifact.GriffonController
    import griffon.metadata.ArtifactProviderFor
    import griffon.transform.MybatisAware
    import org.apache.ibatis.session.SqlSession
    import org.example.mappers.PersonMapper

    import javax.annotation.PostConstruct

    @MybatisAware
    @ArtifactProviderFor(GriffonController)
    class AppController {
        AppModel model

        @PostConstruct
        private void validate() {
            println 'validating controller ...'
            assert this.this$mybatisHandler
        }

        void doit() {
            List out = withSqlSession { String sessionFactoryName, SqlSession session ->
                PersonMapper personMapper = session.getMapper(PersonMapper)
                personMapper.list()*.asMap()
            }
            println out
        }
    }

**Comment by swalton00** [comment]
I did guess that references to the injected item would fail in the
constructor. That's useful to know about
the @javax.annotation.PostConstruct. The code works (without the
PostConstruct annotation) if it it is coded as a service.

What I most like is your response with "withSqlSession" which is very close
to what it used to be (back in 1.x). I find that form MUCH more comfortable
to work with than the form you have on both Hibernate4 and Mybatis plugin
documentation examples (Using the ...Handller to create a new
....CallBack). That leads to nice compact code if all you want to do is
look up a string and return it, but I almost never do that. The
withSqlSession a) means I can revert my code to the original form and b)
leads to code that is slightly more readable..

I will test tomorrow night whether I can do this outside of a service. I
think the constructor issue is just a distraction for the real issue. It
might be that the PostConstruct annotation is needed outside of a
Controller or Service (I don't know yet -- I'll check).

Meanwhile, I'd love to the that snippet on the plugins documentation page
to show using it without the Handler and the CallBack.

Scott Walton

**Comment by swalton00** [comment]
I finally see what the issue is! If you don't "@Inject private Bean bean", the code doesn't work.

This need to be documented under the "2.4 AST Transformation" as the injection is the key to making it work. I would also like to see the "withSqlSession" technique documented there (with, in not instead of the withMyBatisHandler)
