### ISSUE TITLE
Courtesy Request

### ISSUE THREAD

**Issue by EdwardBeckett** [griffon/griffon#48]
Hi Andres... Do you have a startGriffon sh that's compatible with msys bash? I can't seem to find one online and it would be nice to be able to use msys bash to run griffon ...

**Comment by aalmiray** [comment]
Hmm Griffon uses the standard scripts generated by Gradle and Maven, so if they don't support msys Griffon simple does not support it either :cry:

**Comment by EdwardBeckett** [comment]
Well actually Gradle and Maven run well on msys... I tried modifying the script but I wasn't successful ;-( it looks nearly identical to the Gradle script but my bashfoo it weak... it doesn't invoke Griffon... 

[startGriffonMsys](https://gist.github.com/EdwardBeckett/5cc97bee97d93f415916)

**Comment by aalmiray** [comment]
Have you considered asking at the Gradle support forum? There are a couple of enhancements we'd like to make to the application plugin and the StartupScriptGenerator (the class that creates these scripts). If msys is not properly supported b this class then I guess it's a good time to let the Gradle developers know. :smile:

**Comment by EdwardBeckett** [comment]
Sounds good... I'll ping them about it... Thanks @aalmiray  ;)
