### ISSUE TITLE
macApp not working

### ISSUE THREAD

**Issue by oniseijin** [griffon/griffon#57]
Get the error "LSOpenURLsWithRole() failed with error -10810 for the file"

Using  griffon-swing-groovy on Mac OSX 10.10, JRE 1.7.0_40, and executing build, thus griffon 2.2.0 No code changes. 

The pure Java version works packaged in a Jar. 

Info.plist doens't look complete compared to what Griffon 1.5 generated

2.0: 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- created with Gradle, http://gradle.org, and the MacAppBundle plugin, http://code.google.com/p/gradle-macappbundle -->
<plist version='1.0'>
  <dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>English</string>
    <key>CFBundleExecutable</key>
    <string>JavaAppLauncher</string>
    <key>CFBundleIconFile</key>
    <string>griffon.icns</string>
    <key>CFBundleIdentifier</key>
    <string />
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>koan-sql</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>0.1.0-SNAPSHOT</string>
    <key>CFBundleAllowMixedLocalizations</key>
    <string>true</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>JVMMainClassName</key>
    <string />
    <key>JVMOptions</key>
    <array>
      <string>-Dapple.laf.useScreenMenuBar=true</string>
    </array>
    <key>JVMArguments</key>
    <array />
  </dict>
</plist>
```

**Comment by oniseijin** [comment]
Upgrading the plugin to 2.1 didn't help, nor did adding different classpaths. 

change package.groovy to  the below instead of macAppBundle
"edu.sc.seis.macAppBundle" 
and use 2.1.0 version in build.gradle classpath 'edu.sc.seis.gradle:macappbundle:2.1.0'

**Comment by aalmiray** [comment]
The problem is that the `manClassName` project property required by the macappbundle plugin is defined way after the plugin is applied. Switching the definition order fixes the problem. See the diff at https://github.com/griffon/griffon/commit/318f9f3997dad2f14484142a30e2fd0add56bdd6

**Comment by oniseijin** [comment]
Applied the patch to the project
1. JVMClassPath looks good
2. All jars are there
3. JVMMainClass is there
4. JVM itself is copied

But, same error. May very well be the other project's Java launcher, or perhaps OSX 10.10 issue? This time the JDK8 was used (embedded)

**Comment by oniseijin** [comment]
Specific error info: http://apple.stackexchange.com/questions/136975/lsopenurlswithrole-failed-with-error-10810

"The error occurs because JVM failed to launch - the Java application itself has been hardcoded to load libserver.dylib. This file exist for Java 1.6 and older, but not for Java 1.7 and above."
