### ISSUE TITLE
gradle shadow tasks do not completely resolve dependencies

### ISSUE THREAD

**Issue by swalton00** [griffon/griffon#59]
using gradle shadowJar or runShadow not all depencies are completely resolved. Receive ClassNotFoundException at run time for classes that are correctly included with run or distZip tasks

**Comment by aalmiray** [comment]
Hmm looks like a tricky one. The griffon-gradle plugin expands dependencies (i.e, adds more jars to `compile` for example)  when dependencies are resolved, however shadow fails to see them. cc @johnrengelman

**Comment by aalmiray** [comment]
May be related to this https://discuss.gradle.org/t/updating-dependencies-on-configurations/11078

**Comment by aalmiray** [comment]
Looks like this one is fixed alongside with #155
