### ISSUE TITLE
Add support for groovyfx builder controller actions

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#63]
Both buttons and menu items have builder support for controller actions, however actions for other controls cannot be defined in the same way e.g.

builder.with {
    application(title: 'Clicker', pack: true)) {
        button clickAction, label: bind { model.clickCount }
        comboBox otherAction  // <-- ERROR
    }
}

If the event is defined as comboBox(onAction: otherActionAction.onAction) - or by using ActionManager, then the action will be invoked *outside* the UI Thread as the guide suggests.

If its defined as comboBox(onAction: { controller.otherAction } the action will be invoked *inside* the UI Thread.

It would be helpful if it could be defined consistently across all controls and toolkits, or to add an example in the griffon guide.

**Comment by aalmiray** [comment]
Direct invocation of a controller action, such as "controller.otherAction()" will be executed always in the same thread as the caller. Indirect controller action invocation (such as via ActionManager) will always honor threading settings (either implicit or set with @Threading).
