### ISSUE TITLE
StackOverflowError running GroovyFX demo inside GriffonView artifact

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#65]
Example copied from https://github.com/groovyfx-project/groovyfx/blob/master/src/demo/groovy/CustomFieldDemo.groovy

When run the overridden methods in RejectField.replaceText seem to cause the stackoverflow.
In addition an exception occurred using row and column properties on the rejectField, though their fine on textField.

package org.example
import griffon.core.artifact.GriffonView
import griffon.metadata.ArtifactProviderFor
import javafx.scene.control.TextField

@ArtifactProviderFor(GriffonView)
class TestjavafxgroovyView {
    FactoryBuilderSupport builder
    //TestjavafxgroovyModel model
    //TestjavafxgroovyController controller

    void initUI() {
        builder.application(title: application.configuration['application.title'],
            sizeToScene: true, centerOnScreen: true, name: 'mainWindow') {

            registerBeanFactory "rejectField", RejectField

            scene(fill: WHITE, width: 300, height: 400) {
                //gridPane {
                vbox {
                    textField(row: 0, column: 0)
                    //rejectField text: 'only a-z allowed', id: 'input', allow: '[a-z]*', row: 0, column: 0, {
                    rejectField(text: 'only a-z allowed', id: 'input', allow: '[a-z]*') {
                        onMouseEntered { println "enter" }
                        shake = sequentialTransition {
                            rotateTransition to: 3, cycleCount: 3, cycleDuration: 0.1.s
                            rotateTransition 0.1.s, to: 0
                        }
                    }
                }
            }
        }
    }
}

class RejectField extends TextField {
    Closure onReject
    String allow = ".*"

    void replaceText(int start, int end, String text) {
        if (text.matches(allow)) {
            super.replaceText start, end, text
        } else {
            onReject?.call this
        }
    }

    void replaceSelection(String text) {
        if (text.matches(allow)) {
            super.replaceSelection text
        } else {
            onReject?.call this
        }
    }
}

**Comment by shnplr** [comment]
The overflow error does not occur running 'gradle run' from console. It is only occurring from gradle plugin run within IntellijIDEA.  The row, column property not found error occurs in both cases.

**Comment by shnplr** [comment]
this was a problem with my IDE setup - OK to close

**Comment by aalmiray** [comment]
closing per user request.
