### ISSUE TITLE
GroovyFX TreeCell context menu

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#66]
Hi,
This is really a question for the Griffon user mailing list re best approach for adding context menu to TreeCell using groovyfx. The following code appears to work but I wanted to confirm if it was the right approach for Griffon.

1. VIEW
// OK to use single contextMenu instance against all TreeCell instances?
sampleContextMenu = contextMenu() { menuItem(text: "Undo", sayHelloAction) }
treeView(showRoot: false) {
    cellFactory {
        def cell = new SampleTreeCell()
        cell.sampleContextMenu = sampleContextMenu
    }
}

2. 
class SampleTreeCell extends TreeCell {
    ContextMenu sampleContextMenu

    void updateItem(Object item, boolean empty) {
        super.updateItem(item, empty)

        if (empty || item == null) {
            setText(null)
            setGraphic(null)
        } else {
            ...
            if (someCondition)
                setContextMenu(sampleContextMenu)
        }
    }
}

Oracle tutorial shows contextMenu normally being created inside TreeCell, however I want to execute the Griffon action defined on the MenuItem.

Thanks,
Paul

**Comment by shnplr** [comment]
My problem is I'm not sure how to pass/access the TreeCell.TreeItem in the Griffon onAction - or am I misusing how Griffon actions work compared with JavaFX actions?

**Comment by shnplr** [comment]
I've used the following solution:

    treeView(showRoot: false) {
                            cellFactory {
                                def cell = new SampleTreeCell()
                                undoItem = menuItem("Undo") {
                                    onAction { runOutsideUI { controller.sayHello(cell.treeItem) } }
                                }
                                cell.sampleContextMenu.items.add undoItem
    }

    class SampleTreeCell extends TreeCell {
        ContextMenu sampleContextMenu = new ContextMenu() // need ContextMenu per cell
    }

So I'm assuming a Griffon action wont work in this case - the action method needs to be called manually to supply the TreeItem param.

**Comment by aalmiray** [comment]
An alternate invocation would be

    onAction { controller.invokeAction('sayHello', cell.TreeItem }

as this way will invoke the action through the standard mechanism (i.e, ActionHandlers will be in play, such as the threading handler). Invoking the controller action directly as you're doing it will not trigger ActionHandlers at all.

Closing this issue as a solution was found.
