### ISSUE TITLE
jvm -Xdock options in .bat script

### ISSUE THREAD

**Issue by jgoertz** [griffon/griffon#69]
On building distZip under Mac OSX the generated .bat script contains 
set DEFAULT_JVM_OPTS="-Xdock:name=xbrl-regelklient" "-Xdock:icon=$APP_HOME/resources/griffon.icns"

Trying to run this on a Windows platform causes Java to exit with an "Unrecognized option" error. 

Is there a way to circumvent this problem (other than building the distribution on linux or windows platform)?

**Comment by aalmiray** [comment]
Indeed. I wish the JVM would ignore flags that it does not recognize. Gradle 2.4 enables better customizations for the generated scripts, however it breaks Groovy based Griffon projects.
Alternatives are: 

 * build the Windows distribution on windows
 * unpack the distribution generated on OSX, edit the -bat file and repack

We'll find a permanent fix for 2.4.0
