### ISSUE TITLE
NullPointerException invoking controller action with null parameter

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#72]
Griffon 2.3.0 / groovyfx / jdk 1.8.0_45

An exception occurs when invoking an action containing optional null parameter e.g.

    ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
    java.lang.NullPointerException
	    at griffon.exceptions.InstanceMethodInvocationException.formatArguments(InstanceMethodInvocationException.java:60)
	    at griffon.exceptions.InstanceMethodInvocationException.<init>(InstanceMethodInvocationException.java:34)
	    at griffon.util.GriffonClassUtils.invokeInstanceMethod(GriffonClassUtils.java:2416)

In my code treeItem is null if dropped on an empty cell:

    VIEW:
    cell.onDragDropped = { evt ->
	    Dragboard db = evt.getDragboard()
	    Object obj = db.getString()
	    controller.invokeAction("sampleAction", obj, evt.gestureTarget.treeItem)
        ...
    }

    CONTROLLER
    void sampleAction(String val, TreeItem target) {
        ...
    }

Griffons MethodUtils class converts the null parameter to Object, so my current workaround is to declare an additional action method:

    void sampleAction(String val, Object o) {
        sampleAction(val, (TreeItem) null)
    }

The NullPointerException is a secondary issue in Griffons InstanceMethodInvocationException class:

    for (Class<?> type : convertToTypeArray(args)) {
        if (first) {
            first = false;
        } else {
            b.append(",");
        }
        b.append(type.getName());       // <-------------- type is null for null parameter
    }

**Comment by shnplr** [comment]
Hi Andres,

Does the fix support passing of null type in method params or is a workaround still required?

**Comment by aalmiray** [comment]
I'm afraid not. This only solves the NPE but does not solve the method resolution problem.

**Comment by aalmiray** [comment]
It looks like the patch solves the real problem too.
