### ISSUE TITLE
Unsupported major.minor version 52.0 when applying Stats gradle pluging 0.1.4

### ISSUE THREAD

**Issue by ncourtial** [griffon/griffon#73]
Hi,
I'm using jdk 1.8_45 and I follow the developper guide 2.3.0.
After creating a default project using lazybones, I try to launch it using gradle run and I have the following error.

* Where:
Build file 'C:\Users\kurt\sample\build.gradle' line: 44

* What went wrong:
A problem occurred evaluating root project 'sample'.
> java.lang.UnsupportedClassVersionError: org/kordamp/gradle/stats/StatsPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

When i deactivate the Stats plugin, all seems to be good.
 Any Idea?

Cheers?

**Comment by aalmiray** [comment]
Looks like version 0.1.4 of the Stats plugin was compiled with JDK8 as target. I'll make another release making sure JDK7 is set as the baseline.

**Comment by ncourtial** [comment]
Fine, it's OK with jdk 1.7.
Many thanks.

**Comment by aalmiray** [comment]
Version 0.1.5 of stats-gradle-plugin has been released! Grab it now from #bintray https://bintray.com/aalmiray/kordamp/stats-gradle-plugin/0.1.5/view!
