### ISSUE TITLE
How can I use griffon 2.4.0-SNAPSHOT instead of 2.3.0?

### ISSUE THREAD

**Issue by zxxz** [griffon/griffon#75]
Hello, 
I can build griffon 2.4.0-SNAPSHOT running ```gradle``` from the root of the ```development``` branch.
Now I have a question: how can I use griffon 2.4.0-SNAPSHOT instead of 2.3.0 to create a griffon 2.4.0-SNAPSHOT based project? 
Thanks!

**Comment by zxxz** [comment]
I answer my own question :-)
```gradle publishToMavenLocal``` installs griffon 2.4.0-SNAPSHOT to the local maven repository. After that it's just a matter of updating the griffon version in the dependencies.

**Comment by aalmiray** [comment]
This makes me think that build instructions should be added to the repository, just in case :wink:

**Comment by zxxz** [comment]
Well...in that case may I suggest to add also the following instructions?
To build and install locally the lazybones templates that come with 1.4.0-SNAPSHOT version:
```gradle installAllTemplates```
To create a sample project using one of the 1.4.0-SNAPSHOT templates:
```$ lazybones create griffon-javafx-groovy 1.4.0-SNAPSHOT sample```
Now I am all set to start playing for real :-)

**Comment by aalmiray** [comment]
Yes, we'll include that info. Is there something in particular in 2.4.0-SNAPSHOT that you're looking for? So far we've added `core-java8`, some utility methods to `GriffonClassUtils`, template updates and  two new AST transformations targeting JavaFX.

**Comment by zxxz** [comment]
I just wanted to have a clean starting point: create a sample project, run it and start coding with the support of an IDE.
Unfortunately 1.3.0 didn't allow me to do that...
