### ISSUE TITLE
Using griffon preferences plugin to persist config data

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#79]
Not sure if I'm using this plugin correctly for GroovyFX application

1. I used the automatic gradle configuration - "The griffon plugin will take care of the rest given its configuration."

    dependencies {
        griffon 'org.codehaus.griffon.plugins:griffon-preferences-plugin:1.1.0'
    }

This seems to create a preferences with binary data

I removed that and added instead the manual step:

    dependencies {
        compile 'org.codehaus.griffon.plugins:griffon-preferences-json:1.1.0'
    }

This seems a much better approach as it brings the core + json libraries as dependencies, where as the first option does not.  I dont understand the benefit of using the automatic approach

2. I tried to use the example

    @Preference(defaultValue='Sample')
    String title

After closing the application the JSON was written as expected.  However when I attempted to set a new value at runtime the new value did not persist.  Only the file default.json exists - should another file be created for non default values.  I also tried adding the @FXObservable but did not help

    @Preference(defaultValue='Sample')
    @FXObservable
    String title

Controller:

    runInsideUISync {
        model.title = "sample2"
    }    

3. Does the preferences plugin support serialization of lists?

    @Preference
    @FXObservable ObservableList sampleList

I am not sure if this is a bug or I'm doing something wrong here - probably the latter.

Thanks for any input,
Paul

**Comment by aalmiray** [comment]
Answers to your questions:

1. The automatic configuration allows for quick setups. The JSON module brings additional dependencies and thus is set as optional. Same as the YAML module.

2. Preference values (once updated) are not automatically synced.This is an act that must be consciously executed by the developer, thus explicit calls tom `PreferencesManager.save()` must be made. I believe this is missing from the current guide given https://github.com/griffon-plugins/griffon-preferences-plugin/issues/1

3. I think a custom `ObservableListPropertyEditor` must be created for this case. There's no simple way to provide such editor in the core package as each element inside the `List` can potentially be converted by another editor.

A solution must be found for `List`,  `Map` and `Set`.

Finally, it's OK to raise discussions here at the issues page, however these topics are more related to the `preferences` plugin, which has its own issues page. Also, general discussions are better handled by the Mailing List at http://griffon-user.74797.x6.nabble.com/

Thanks :smile:

**Comment by aalmiray** [comment]
Closing due to https://github.com/griffon-plugins/griffon-preferences-plugin/issues/1 and https://github.com/griffon-plugins/griffon-preferences-plugin/issues/5
