### ISSUE TITLE
Griffon lazybones templates fail to populate version field in project build

### ISSUE THREAD

**Issue by swalton00** [griffon/griffon#80]
If I create new griffon app with "lazybones create griffon-javafx-groovy ." it fails to populate the griffon property "version" leaving it as 

    version = '${griffon_version}' 

If I create the app using a specific directory name it create takes the version from the default value, so the end result is the correct 

    version = '2.3.0'

**Comment by aalmiray** [comment]
Can't reproduce with lazybones 0.8.1
Here's the transcript of a console session, where the aforementioned command is used sucessfully

    [test]> lazybones --version
    Lazybones version 0.8.1
    [test]> lazybones create griffon-javafx-groovy .
    Creating project from template griffon-javafx-groovy (latest) in current directory
    Define value for 'group' [org.example]: 
    Define value for 'artifactId' [test]: 
    Define value for 'version' [0.1.0-SNAPSHOT]: 
    Define value for 'griffonVersion' [2.3.0]: 
    Define value for 'package' [org.example]: 
    Define value for 'className' [Test]: 

    Basic Griffon JavaFX/Groovy project
    -----------------------------------

    You have just created a basic Griffon application with JavaFX as the UI toolkit
    and Groovy as the main language. The project has the following file structure

        .
        ├── build.gradle
        ├── griffon-app
        │   ├── conf
        │   ├── controllers
        │   ├── i18n
        │   ├── lifecycle
        │   ├── models
        │   ├── resources
        │   ├── services
        │   └── views
        ├── pom.xml
        └── src
            ├── integration-test
            │   └── groovy
            ├── main
            │   ├── groovy
            │   └── resources
            └── test
                ├── groovy
                └── resources

    Simply add your source files to `src/main/groovy`, your test cases to
    `src/test/groovy` and then you will be able to build your project with

        gradle build
        gradle test
        gradle run

    Don't forget to add any extra JAR dependencies to `build.gradle`!

    If you prefer building with Maven then execute the following commands

        mvn compile
        mvn test
        mvn -Prun

    Don't forget to add any extra JAR dependencies to `pom.xml`!


    Project created in current directory!
    [test]> !grep
    grepc -r "version" .
    ./.lazybones/stored-params.properties:version=0.1.0-SNAPSHOT
    ./build.gradle:        classpath 'com.github.ben-manes:gradle-versions-plugin:0.10.1'
    ./build.gradle:    version = '2.3.0'
    ./build.gradle:apply plugin: 'com.github.ben-manes.versions'
    ./build.gradle:    compile "org.codehaus.griffon:griffon-guice:${griffon.version}"
    ./build.gradle:    testCompile "org.codehaus.griffon:griffon-javafx-test:${griffon.version}"
    ./build.gradle:    functionalTestCompile "org.codehaus.griffon:griffon-javafx-test:${griffon.version}"
    ./gradle/docs.gradle:    options.version     = true
    ./gradle/docs.gradle:    options.windowTitle = "$project.name $project.version API"
    ./gradle/docs.gradle:    options.docTitle    = "$project.name $project.version API"
    ./gradle/docs.gradle:    windowTitle = "$project.name $project.version API"
    ./gradle/docs.gradle:    docTitle = "$project.name $project.version API"
    ./gradle/docs.gradle:    header = "$project.name $project.version API"
    ./gradle/javafx-plugin.gradle: * The script will add the latest version of the plugin to the build script
    ./gradle/javafx-plugin.gradle: * own build script and define your own repository and version for the plugin.
    ./gradle/package.gradle:        filter(ReplaceTokens, tokens: ['griffon.version': griffon.version])
    ./gradle/package.gradle:    outputFile = file("$buildDir/distributions/${project.name}-${version}-installer.jar")
    ./gradle/package.gradle:        'app.version'     : project.version,
    ./gradle/package.gradle:        'app.subpath'     : "${project.name}-${project.version}",
    ./gradle/package.gradle:        'app.java.version': targetCompatibility
    ./gradle/publishing.gradle:            'Created-By': "${System.properties['java.version']} (${System.properties['java.vendor']} ${System.properties['java.vm.version']})".toString(),
    ./gradle/publishing.gradle:            'Specification-Version': project.version,
    ./gradle/publishing.gradle:            'Implementation-Version': project.version
    ./gradle.properties:version = 0.1.0-SNAPSHOT
    ./gradlew.bat:%JAVA_EXE% -version >NUL 2>&1
    ./griffon-app/resources/application.properties:application.version=@application.version@
    ./maven/ant-macros.xml:                        token="application.version"
    ./maven/ant-macros.xml:                        value="${project.version}"/>
    ./maven/ant-macros.xml:                    <filter token="griffon.version"
    ./maven/ant-macros.xml:                            value="${griffon.version}"/>
    ./maven/distribution/bin/test.bat:%JAVA_EXE% -version >NUL 2>&1
    ./maven/prepare-izpack.xml:        source="${project.build.directory}/distributions/${project.artifactId}-${project.version}-dist/${project.artifactId}-${project.version}"/>
    ./maven/prepare-izpack.xml:            output="${project.build.directory}/distributions/${project.artifactId}-${project.version}-installer.jar"
    ./maven/prepare-izpack.xml:        <property name="app.version" value="${project.version}"/>
    ./maven/prepare-izpack.xml:        <property name="app.subpath" value="${project.artifactId}-${project.version}"/>
    ./maven/prepare-izpack.xml:        <property name="app.java.version" value="${compiler.target.level}"/>
    ./pom.xml:    <version>0.1.0-SNAPSHOT</version>
    ./pom.xml:        <version>1.3.0</version>
    ./pom.xml:        <griffon.version>2.3.0</griffon.version>
    ./pom.xml:            <version>1.2.17</version>
    ./pom.xml:            <version>1.7.12</version>
    ./src/main/izpack/install.xml:<installation version="1.0">
    ./src/main/izpack/install.xml:    <variable name="appVersion" value="@{app.version}"/>
    ./src/main/izpack/install.xml:    <javaversion>@{app.java.version}</javaversion>
    ./src/main/izpack/install.xml:    <appversion>@{app.version}</appversion>
    ./src/main/izpack/resources/asl2.html:      and conversions to other media types.
    ./src/main/izpack/resources/asl2.html:      the original version of the Work and any modifications or additions
    ./src/main/izpack/resources/emptyShortcutSpec.xml:<?xml version="1.0" encoding="iso-8859-1" standalone="yes" ?>
    ./src/main/izpack/resources/processSpec.xml:<?xml version="1.0" encoding="iso-8859-1" standalone="yes" ?>
    ./src/main/izpack/resources/RegistrySpec.xml:<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
    ./src/main/izpack/resources/RegistrySpec.xml:               keypath="SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\@{app.title}-@app.version@"
    ./src/main/izpack/resources/RegistrySpec.xml:               string="@{app.title} @app.version@"/>
    ./src/main/izpack/resources/RegistrySpec.xml:               keypath="SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\@{app.title}-@app.version@"
    ./src/main/izpack/resources/RegistrySpec.xml:               keypath="SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\@{app.title}-@app.version@"
    ./src/main/izpack/resources/unixShortcutSpec.xml:<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
    ./src/main/izpack/resources/unixShortcutSpec.xml:    <programGroup defaultName="@{app.title}-@app.version@" location="applications"/>
    ./src/main/izpack/resources/unixShortcutSpec.xml:            name="@{app.title} @app.version@ Uninstaller"
    ./src/main/izpack/resources/unixShortcutSpec.xml:            description="This uninstalls @{app.title} @app.version@">
    ./src/main/izpack/resources/winShortcutSpec.xml:<?xml version="1.0" encoding="iso-8859-1" standalone="yes" ?>
    ./src/main/resources/log4j.properties:log4j.appender.stdout.layout.ConversionPattern=[%d] [%t] %-5p %-c - %m%n

**Comment by aalmiray** [comment]
I must add that I tested versions 1.3.0 (stable) and 1.4.0-SNAPSHOT (unstable) of the `griffon-javafx-groovy` template, with both lazybones 0.8.1 and 0.8. The result was the same. All value placeholders were successfully converted.

**Comment by swalton00** [comment]
I have 1.7.1 on this computer.  I'll try again in after I leave work and
verify which version is on that machine, and upgrade lazybones, if that is
what the issue is.

**Comment by swalton00** [comment]
Pulled down 0.8.1 and built the same prototype project -- builds fine.

If I could (or knew how), I'd close this one. It's resolved by lazybones
0.8.1 (and that version looks to have a couple of useful new features!)

Scott

**Comment by aalmiray** [comment]
Perfect! Thanks for checking again :smile:
