### ISSUE TITLE
NullPointerException when binding to a model property, ok with explicit call on getter

### ISSUE THREAD

**Issue by marcpa00** [griffon/griffon#84]
Using a groovyfx builder, a NPE is raised in Util.isJavaBeanPropertyWritable() when the property name is used, but is ok if the javafx property getter is used.

NPE when:
```
        builder.with {
            content = anchorPane {
                label(leftAnchor: 14, topAnchor: 14,
                        text: application.messageSource.getMessage('name.label'))
                textField(leftAnchor: 172, topAnchor: 11, prefWidth: 200,
                        text: bind(model.inputProperty))
```

OK when:
```
        builder.with {
            content = anchorPane {
                label(leftAnchor: 14, topAnchor: 14,
                        text: application.messageSource.getMessage('name.label'))
                textField(leftAnchor: 172, topAnchor: 11, prefWidth: 200,
                        text: bind(model.inputProperty()))

```

This is using java version "1.8.0_51" and griffon 2.3.0

Full stacktrace:
```
[2015-08-24 13:23:58,539] [JavaFX Application Thread] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
java.lang.NullPointerException
        at groovyx.javafx.binding.Util.isJavaBeanPropertyWritable(Util.java:69)
        at groovyx.javafx.binding.Util.getJavaBeanFXProperty(Util.java:80)
        at groovyx.javafx.binding.Util$getJavaBeanFXProperty$0.call(Unknown Source)
        at groovyx.javafx.binding.BindingHolder.resolve(BindingHolder.groovy:99)
        at groovyx.javafx.binding.BindingHolder$resolve$0.call(Unknown Source)
        at groovyx.javafx.factory.FXHelper$__clinit__closure26.doCall(FXHelper.groovy:448)
        at groovyx.javafx.factory.FXHelper.fxAttribute(FXHelper.groovy:533)
        at groovyx.javafx.factory.FXHelper$fxAttribute$0.callStatic(Unknown Source)
        at groovyx.javafx.factory.FXHelper$fxAttribute$0.callStatic(Unknown Source)
        at groovyx.javafx.factory.FXHelper.fxAttributes(FXHelper.groovy:585)
        at groovyx.javafx.factory.FXHelper$fxAttributes.call(Unknown Source)
        at groovyx.javafx.factory.FXHelper$fxAttributes.call(Unknown Source)
        at groovyx.javafx.factory.NodeFactory$__clinit__closure1.doCall(NodeFactory.groovy:32)
        at org.example.Tab3View$_initUI_closure1$_closure2.doCall(Tab3View.groovy:21)
        at org.example.Tab3View$_initUI_closure1$_closure2.doCall(Tab3View.groovy)
        at org.example.Tab3View$_initUI_closure1.doCall(Tab3View.groovy:17)
        at org.example.Tab3View.initUI(Tab3View.groovy:16)
        at org.example.AppView.mvcGroupInit(AppView.java:34)
```

**Comment by aalmiray** [comment]
The code looks like the one found at http://griffon-framework.org/tutorials/4_javafx_views.html
I've been unable to reproduce the problem with neither 2.3.0 nor 2.4.0-SNAPSHOT :cry:

**Comment by marcpa00** [comment]
Yes exactly, I was following the tutorial.  

Could it be a problem with some cached jars or classes ?  
I tried cleaning my ~/.gradle/caches with same result.  Anything else I could try to wipe out ?

Here is more info on my environment:

[marcpa@marcpaquette app]$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
[marcpa@marcpaquette app]$ gw -version
Using gradle at '/Users/marcpa/Code/griffon-learning/app/gradlew' to run buildfile '/Users/marcpa/Code/griffon-learning/app/build.gradle':

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.10.5 x86_64

**Comment by aalmiray** [comment]
Hmm I've got the same settings except OSX is 10.10.3 from my side.
Bumped Gradle to 2.6 and Java to 8u60 -> no error.
I guess the next thing to try is to upgrade OSX to 10.10.5

**Comment by marcpa00** [comment]
Looks like it; I removed my ~/.groovy/lib and my ~/.gradle entirely, did a « gw run » and got the same error.  

I got the same problem with another griffon 2.3.0 project I created from scratch, but I thought I did something wrong… Now I’m following the tutorial step by step, but I retype code (I tend to remember more things when I type them…); I should probably try by downloading the code from github.

**Comment by aalmiray** [comment]
Well, the full source is available at https://github.com/griffon/griffon/tree/development/tutorials/javafx-app
You should be able to launch `gw` directly from there, although you'll need to update the project to Griffon 2.3.0 as the build file still uses 2.2.0

**Comment by marcpa00** [comment]
Got a new copy of master branch, went to ‘tutorials/javafx-app’, changed build.gradle to use griffon-2.3.0 and issued a ‘gw run’ from there and now got another error :

[marcpa@marcpaquette javafx-app]$ gw run
Using gradle at '/Users/marcpa/Code/griffon-2/tutorials/javafx-app/gradlew' to run buildfile '/Users/marcpa/Code/griffon-2/tutorials/javafx-app/build.gradle':

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
:compileJava
:compileGroovy
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
/Users/marcpa/Code/griffon-2/tutorials/javafx-app/build/tmp/compileGroovy/groovy-java-stubs/org/example/Tab3View.java:10: error: Tab3View does not implement griffon.core.artifact.GriffonView
@griffon.metadata.ArtifactProviderFor(value=griffon.core.artifact.GriffonView.class) public class Tab3View
                                                                                            ^
1 error
startup failed:
Compilation failed; see the compiler error output for details.

1 error

:compileGroovy FAILED

:-(

AST xform not kicking in ?

**Comment by aalmiray** [comment]
Ah yes, indeed. Gradle 2.4 doesn't work with Groovy based projects. This is a known issue. Either downgrade to 2.3 or upgrade to 2.5+. I'll update the repo too.

**Comment by marcpa00** [comment]
Ok, it was my bad : when editing SampleModel.java I made an error : the `getInputProperty()` / `getOutputProperty()` were defined as returning `String` instead of `StringProperty`, as seen in this diff between what I created and the tutorial content from github:

```java
--- SampleModel.java	2015-08-24 20:49:57.000000000 -0400
+++ /Users/marcpa/Code/griffon-2/tutorials/javafx-app/griffon-app/models/org/example/SampleModel.java	2015-08-24 16:30:38.000000000 -0400
@@ -21,8 +21,8 @@
         return input;
     }

-    public String getInputProperty() {
-        return inputProperty().get();
+    public final StringProperty getInputProperty() {
+        return inputProperty();
     }

     public String getInput() {
@@ -41,8 +41,8 @@
         return output;
     }

-    public String getOutputProperty() {
-        return outputProperty().get();
+    public final StringProperty getOutputProperty() {
+        return outputProperty();
     }

     public String getOutput() {
```

Once I put the correct code (and use gradle 2.6), everything is ok !

Thanks for your kind help ! (as always)
