### ISSUE TITLE
Add environment setting to lazybones templates

### ISSUE THREAD

**Issue by swalton00** [griffon/griffon#85]
In the lazybones templates, please add an environment setting to the build.gradle to set the appropriate environment from the gradle command as:

    if (project.hasProperty('environment')) {
        applicationDefaultJvmArgs = ['-Dgriffon.env=' + environment]
    }

    run {
        jvmArgs = ['-Dgriffon.env=dev']
    }

**Comment by aalmiray** [comment]
Looks like this feature already exists https://github.com/griffon/griffon/blob/development/subprojects/gradle-griffon-plugin/src/main/groovy/org/codehaus/griffon/gradle/GriffonPlugin.groovy#L283-L295

use `-DgriffonEnv=` to pass the desired value.

**Comment by swalton00** [comment]
verified - please close

I was looking for "enviroment", when I should be using:

gradlew -PgriffonEnv=prod run

**Comment by swalton00** [comment]
I have closed it -- I need to run as:

gradlew -PgriffonEnv=<desired>

On Thu, Aug 27, 2015 at 10:09 AM, Andres Almiray <notifications@github.com>
wrote:

> Looks like this feature already exists
> https://github.com/griffon/griffon/blob/development/subprojects/gradle-griffon-plugin/src/main/groovy/org/codehaus/griffon/gradle/GriffonPlugin.groovy#L283-L295
>
> use -DgriffonEnv= to pass the desired value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/griffon/griffon/issues/85#issuecomment-135446230>.
>



-- 
Scott Walton
