### ISSUE TITLE
Unable to build 2.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#86]
Step2 of https://github.com/griffon/griffon/blob/development/BUILDING.adoc
Binaries
Building

    Make sure your environment is setup correctly by invoking gradle or gradlew.

    Make a full build invoking gradle build.

C:\>gradle -version
------------------------------------------------------------
Gradle 2.6
------------------------------------------------------------

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Windows 7 6.1 amd64

C:\dev\git_local\griffon>gradle build
...
:griffon-groovy:license UP-TO-DATE
:griffon-groovy:test

griffon.util.Xml2GroovySpec > Parse application.xml from file FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at Xml2GroovySpec.groovy:38

griffon.util.Xml2GroovySpec > Parse application.xml from reader FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at Xml2GroovySpec.groovy:38

griffon.util.Xml2GroovySpec > Parse application.xml from inputStream FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at Xml2GroovySpec.groovy:38

griffon.util.Xml2GroovySpec > Parse application.xml from uri FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at Xml2GroovySpec.groovy:38

griffon.util.Xml2GroovySpec > Parse application.xml from gpathResult FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at Xml2GroovySpec.groovy:38

griffon.util.Xml2GroovySpec > Parse application.xml from String FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at Xml2GroovySpec.groovy:54
Test results griffon-groovy: FAILURE (61 tests, 55 passed, 6 failed, 0 skipped)

61 tests completed, 6 failed
:griffon-groovy:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':griffon-groovy:test'.
> There were failing tests. See the report at: file:///C:/dev/git_local/griffon/subprojects/griffon-groovy/build/reports/tes
ts/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 44.461 secs

**Comment by aalmiray** [comment]
This appears to be a Windows path issue although we have had successful builds on Appveyor.

**Comment by shnplr** [comment]
Hi Andres,
I think the issue is due to line endings. It looks like griffon.util.Xml2Groovy converts Windows line endings to Unix ie. CRLF to LF. I guess the solution is either:
1. ensure users checkout the git repository preserving line endings 
2. modify Xml2Groovy.java to preserve line endings
3. change the test to ignore line endings in the comparison

Cheers,
Paul

**Comment by shnplr** [comment]
I've work around the issue (option 3) using normalize(), and built successfully.

@@ -35,7 +35,7 @@ class Xml2GroovySpec extends Specification {
         String output = Xml2Groovy.instance.parse(input)
 
         expect:
-        expected.trim() == output.trim() || expected8.trim() == output.trim()
+        expected.trim().normalize() == output.trim() || expected8.trim().normalize() == output.trim()
 
         where:
         type          | input
@@ -51,7 +51,7 @@ class Xml2GroovySpec extends Specification {
         String output = Xml2Groovy.instance.parseText(new File(APPLICATION_XML).text)
 
         expect:
-        expected.trim() == output.trim() || expected8.trim() == output.trim()
+        expected.trim().normalize() == output.trim() || expected8.trim().normalize() == output.trim()
     }
