### ISSUE TITLE
Update griffon site url at github

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#87]
The link to Griffon at https://github.com/griffon/griffon title section needs updating:-

http://griffon.codehaus.org

**Comment by aalmiray** [comment]
Fixed. Thanks :smile:

**Comment by shnplr** [comment]
oh dear...the parent page and I suspect many sub-projects still refer to the old link as well ;)

**Comment by aalmiray** [comment]
which parent page are we talking about? If it's https://github.com/griffon then yes, all subprojects under that organization belong to Griffon 1.x. All new Griffon 2.x plugins are located at https://github.com/griffon-plugins

**Comment by shnplr** [comment]
Yes https://github.com/griffon + subprojects. Whether 1.x or 2.x I'm assuming that http://griffon.codehaus.org is invalid URL.

**Comment by aalmiray** [comment]
That's right, but given that they are legacy projects now there's little reason to update them.
