### ISSUE TITLE
`groovy.lang.MissingPropertyException: No such property` when using a FXML resource

### ISSUE THREAD

**Issue by marcpa00** [griffon/griffon#88]
I have a hard time understanding what's going on with this : when the FXML is using a `SplitPane` as root node, I get a `MissingPropertyException`.  When an `AnchorPane` is used instead, everything is ok !

I made a griffon project to show this : https://github.com/marcpa00/cannot-resolve-property-fxml

**Comment by aalmiray** [comment]
It looks like FXMLFactory was getting confused when resolving the node's id. Luckily Griffon has additional means to find elements in the hierarchy.

**Comment by marcpa00** [comment]
Man, you Rock !
