### ISSUE TITLE
Add debug configuration to build.gradle in project templates

### ISSUE THREAD

**Issue by aalmiray** [griffon/griffon#93]
A few people have asked about the settings for enabling remote debugging of a Griffon application. Here's one possible solution (append this to `build.gradle`):

    if (hasProperty('debugRun') && project.debugRun) {
        run {
            jvmArgs '-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005'
            debug true
        }
    }

then run the project with `gradle -PdebugRun=true run`; open a remote debugging session on your IDEA and connect to the paused process. voilà!

**Comment by swalton00** [comment]
i find I can debug easily in IntelliJ, but there are a couple of important
steps. The build.gradle file must be current and must have been imported
into Intellij. The best way I have found to do this seems to be to do a
"File" "Open" of the build.gradle file.I do this every time I change the
dependencies, and tell Idea to delete the old project and use the new one.
At this point I can then setup a "gradle run" configuration (it needs to be
a gradle task, usually run) and I can either run it or debug it. This also
has the very useful side effect of informing IntelliJ of most of the
dependencies, so most of the red error messages disappear.

Scott Walton

**Comment by aalmiray** [comment]
Right. These settings allow you to run the application from the command line and attach a Remote debugging session from IntelliJ.
