### ISSUE TITLE
JavaFX complex controls

### ISSUE THREAD

**Issue by kastork** [griffon/griffon#95]
Are javafx complex controls like TableView, TreeTableView and TreeView supported?  If so, request docs on binding for these.

**Comment by aalmiray** [comment]
All JavaFX components are supported. There's no need for special binding support for the Griffon side for now. All standard binding mechanisms should work.

You could also have a look at https://github.com/TomasMikula/ReactFX (and EasyBind, form the same author) for more complex binding alternatives than the ones provided by JavaFX8

**Comment by kastork** [comment]
Finally got it to work.. but it feels pretty hack-ish.

```groovy
void initUI()
  {

    builder.with {
      content = builder.fxml(resource('/edu/nps/cxxitools/info.fxml')) {

        def tv = bean(
            rcTable,
            columns: bind(model.columnsProperty),
            items: bind(model.rcTableProperty)
        )
        tv.columns.each {TableColumn col ->
          if (col.id == 'nameCol')
          {
            col.setCellValueFactory(
                new PropertyValueFactory<Pair, String>("name")
            )
          }
          if (col.id == 'valCol')
          {
            col.setCellValueFactory(
                new PropertyValueFactory<Pair, String>("value")
            )
          }
        }
      }
    }

    controller.initRcTable()
  ...
```

I couldn't figure out a way to have the builder recognize the TableColumn bean names.

**Comment by aalmiray** [comment]
This appears to be more of an issue on the GroovyFX side than on the Griffon side
